version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: npm install
      - run: CI=false npm run-script build
  test:
    docker:
      - image: weltn24/up-docker-node-chrome-headless # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: npm install
      - run: npm test

workflows:
  version: 2.1
  build_test:
    jobs:
      - build
      - test